# Generated by Django 4.0.2 on 2022-03-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastNamePapa', models.CharField(max_length=30)),
                ('lastNameMama', models.CharField(max_length=30)),
                ('names', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('dateBorn', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amailcontact.city')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amailcontact.human')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amailcontact.human')),
            ],
        ),
    ]
