# Generated by Django 4.0.2 on 2022-03-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ac_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ac_name', models.CharField(max_length=50)),
                ('ac_credits', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
